sonar.projectKey=BorderFrame-Layout
sonar.projectName=BorderFrameLayout
sonar.projectVersion=1.0
sonar.sources=BorderFrameLayout
sonar.java.binaries=BorderFrameLayout
sonar.token=squ_f9fa0b1278cd7bd4b9759d1988a42fed4f13df3a
